#!/bin/bash

FILE_NAME="$1"
# Checking that filename argument is provided
if [[ -z "$FILE_NAME" ]]; then
    echo "Usage: $0 <file_name>" >&2
    exit 1
fi
# Check that the given file exists
if [[ ! -f "$FILE_NAME" ]]; then
    echo "Error: File '$FILE_NAME' not found." >&2
    exit 1
fi

# Check wether file is readable or not
if [[ ! -r "$FILE_NAME" ]]; then
    echo "Error: File '$FILE_NAME' is not readable." >&2
    exit 1
fi

# Check that file is filled with the content
if [[ ! -s "$FILE_NAME" ]]; then
    echo "Error: File '$FILE_NAME' is empty." >&2
    exit 1
fi
# Find the max ID
maximum_id=$(awk -F';' 'NR > 1 && $1 ~ /^[0-9]+$/ && $1 > max { max = $1 } END { print max+0 }' "$FILE_NAME")
made_up_id=$((maximum_id + 1))

head -n 1 "$FILE_NAME" | tr ';' '\t' | tr -d '\r' | tr -cd '\11\12\15\40-\176'
echo

#Processing all rows
tail -n +2 "$FILE_NAME" | while IFS= read -r line; do
    line="${line//$'\r'/}"

    # Splitting the fields by the use of  ';'
    IFS=';' read -ra fields <<< "$line"

    # Assignment of new ID if missing
    if [[ -z "${fields[0]}" ]]; then
        fields[0]=$made_up_id
        ((made_up_id++))
    fi

    #Convert decimal commas to dots ONLY  and not the ones that are already in the mechanics and domain list:
    #Rating Average (index 8) and Complexity Average (index 10)
    fields[8]="${fields[8]//,/.}"
    fields[10]="${fields[10]//,/.}"

    #ASCII-cleaned
    output_line=$(printf "%s\t" "${fields[@]}")
    echo "${output_line%$'\t'}" | tr -cd '\11\12\15\40-\176'
done

